import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/lib/auth";
import { ProgressProvider } from "@/lib/progress";
import CookieConsent from "@/components/CookieConsent";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const siteUrl = "https://vibecodeyour.app";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "Vibe Code Your App - Ship 30+ iOS Apps/Year Solo",
    template: "%s | Vibe Code Your App",
  },
  description:
    "The complete vibecoding methodology for building and shipping profitable iOS apps at scale using AI. 16 modules. 54+ lessons. From idea to App Store.",
  keywords: [
    "vibecoding",
    "iOS development",
    "AI coding",
    "Claude Code",
    "SwiftUI",
    "app development course",
    "solo developer",
    "ship apps",
    "mobile app business",
  ],
  authors: [{ name: "David Pavlovschii", url: siteUrl }],
  creator: "Doved Studio",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    siteName: "Vibe Code Your App",
    title: "Vibe Code Your App - Ship 30+ iOS Apps/Year Solo",
    description:
      "The complete vibecoding methodology. 33+ apps shipped by one developer using AI. Learn the system — prompt engineering, business validation, system design.",
    // Dynamic OG image generated by /src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Vibe Code Your App - Ship 30+ iOS Apps/Year Solo",
    description:
      "The complete vibecoding methodology. 33+ apps shipped by one developer using AI. Learn the system.",
    creator: "@davidpavlovs",
    // Dynamic Twitter image generated by /src/app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <AuthProvider>
          <ProgressProvider>
            {children}
            <CookieConsent />
          </ProgressProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
